services:
  - type: web
    name: ims-inventory-system
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: MYSQL_HOST
        value: bsxy5i1rcm0shnblmbod-mysql.services.clever-cloud.com
      - key: MYSQL_USER
        value: ufet9steolrjpkus
      - key: MYSQL_PASSWORD
        value: a2fSxd3z6rJDyxiXmw9c
      - key: MYSQL_DATABASE
        value: bsxy5i1rcm0shnblmbod
